name: Deploy Maven site to GitHub Pages

on:
  workflow_dispatch: {}
  issues:
    types: [opened, edited, deleted]
  release: {}
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  issues: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn clean test verify --file pom.xml
  build:
    runs-on: ubuntu-24.04
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Deploy site
        run: mvn clean site --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
