name: Deploy Maven Release

on:
  workflow_dispatch: {}
  release:
    types: [published]
concurrency:
  group: release
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
env:
  GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
      - name: Test with Maven
        run: mvn --batch-mode test verify --file pom.xml
  build:
    runs-on: ubuntu-24.04
    needs: test
    environment:
      name: release
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
      - name: Set GitHub Credentials
        run: |
          git config --global user.name "Coderic"
          git config --global user.email "coderic@coderic.org"
      - name: Build package
        run: mvn --batch-mode package --file pom.xml
      - name: Prepare package
        run: mvn --batch-mode release:prepare -DtagNameFormat=@{project.version} --file pom.xml
      - name: Deploy package
        id: deployment
        run: mvn --batch-mode release:perform -DtagNameFormat=@{project.version} --file pom.xml
